In [4]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

##  Numpy

To create an array of zeros or ones or any other number:

In [5]:
import numpy as np
np.zeros(5)
np.ones(5)
np.full(10, 2.5) # fill with 2.5 10 times

array([0., 0., 0., 0., 0.])

array([1., 1., 1., 1., 1.])

To create a range:

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

To create an array between two numbers

In [7]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

To create a multi-dimensional array


In [8]:
np.zeros((5,2)) # (rows,columns)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Create a numpy array from an existing list of lists


In [11]:
my_list = [[1,2,3], [4,5,6]]
my_np_array = np.array(my_list)
type(my_list)
type(my_np_array)

list

numpy.ndarray

Generate a random array with a seed

In [13]:
np.random.seed(42)
np.random.rand(5,2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])

Multiply every element in the array by 100


In [14]:
100 * np.random.rand(3,3)

array([[ 2.05844943, 96.99098522, 83.24426408],
       [21.23391107, 18.18249672, 18.34045099],
       [30.4242243 , 52.47564316, 43.19450186]])

Specify the range of numbers for rand

In [15]:
np.random.randint(low=0, high=5, size=(3,3))

array([[0, 2, 2],
       [1, 3, 3],
       [2, 3, 3]])

Add two vectors together


In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

Multiply two vectors together

In [18]:
a.dot(b)

np.int64(32)

Multiply a matrix and vector together


In [23]:
c = np.random.randint(low=0, high=5, size=(3,3))
print(c)
c.dot(a)

[[3 0 4]
 [4 1 4]
 [1 0 3]]


array([15, 18, 10])

Multiply a matrix and vector together

In [26]:
d = np.random.randint(low=10, high=13, size=(3,3))
print(d)
print(c.dot(d))

[[10 11 12]
 [11 10 12]
 [10 11 10]]
[[ 70  77  76]
 [ 91  98 100]
 [ 40  44  42]]


Create an identity matrix


In [36]:
I = np.eye(3)
print(I)
print(d.dot(I))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[10. 11. 12.]
 [11. 10. 12.]
 [10. 11. 10.]]


Get the inverse of a matrix

In [39]:
d_inv = np.linalg.inv(d)
print(d_inv)
print(d_inv.dot(d))

[[-0.76190476  0.52380952  0.28571429]
 [ 0.23809524 -0.47619048  0.28571429]
 [ 0.5        -0.         -0.5       ]]
[[ 1.00000000e+00  3.88578059e-16 -3.33066907e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


Transpose a matrix

In [41]:
dT = d.T
print(d)
print(dT)

[[10 11 12]
 [11 10 12]
 [10 11 10]]
[[10 11 10]
 [11 10 11]
 [12 12 10]]
